{
 "title": "TLS-ifaceTLSoIP",
 "description": "TLS-ifaceTLSoIP-Übersicht",
 "tags": [
  "spring",
  "grpc",
  "java",
  "kafka",
  "mongo"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Up-Time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "min(process_uptime_seconds{app=\"tls-ifacetlsoip\"})"
    }
   ]
  },
  {
   "title": "Running Instances",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(up{app=\"tls-ifacetlsoip\"})"
    }
   ]
  },
  {
   "title": "Expected instances",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas{deployment=\"tls-ifacetlsoip\"})"
    }
   ]
  },
  {
   "title": "CPU-Usage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(process_cpu_usage{app=\"tls-ifacetlsoip\"}) * 100"
    }
   ]
  },
  {
   "title": "RAM-Usage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(sum(jvm_memory_used_bytes{app=\"tls-ifacetlsoip\"}) by (instance)) / min(sum(jvm_memory_max_bytes{app=\"tls-ifacetlsoip\"}) by (instance))"
    }
   ]
  },
  {
   "title": "Open Files",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(process_files_open_files{app=\"tls-ifacetlsoip\"})"
    }
   ]
  },
  {
   "title": "Resource-Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "max(process_cpu_usage{app=\"tls-ifacetlsoip\"}) * 100",
       "legendFormat": "CPU"
      }
     ]
    },
    {
     "title": "RAM",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "min(sum(jvm_memory_max_bytes{app=\"tls-ifacetlsoip\", area=\"heap\"}) by (instance))",
       "legendFormat": "Max heap Memory"
      },
      {
       "expr": "max(sum(jvm_memory_used_bytes{app=\"tls-ifacetlsoip\"}) by (instance, area)) by (area)",
       "legendFormat": "Current {{area}} Memory"
      }
     ]
    }
   ]
  },
  {
   "title": "Outgoing gRPC Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sent",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(grpc_client_processing_duration_seconds_count{app=\"tls-ifacetlsoip\"}[1m]))",
       "legendFormat": "Total Requests"
      },
      {
       "expr": "sum(increase(grpc_client_requests_sent_messages_total{app=\"tls-ifacetlsoip\"}[1m])) / sum(increase(grpc_client_processing_duration_seconds_count{app=\"tls-ifacetlsoip\"}[1m]))",
       "legendFormat": "Messages per Request"
      },
      {
       "expr": "sum(increase(grpc_client_responses_received_messages_total{app=\"tls-ifacetlsoip\"}[1m])) / sum(increase(grpc_client_processing_duration_seconds_count{app=\"tls-ifacetlsoip\"}[1m]))",
       "legendFormat": "Responses per Request"
      }
     ]
    },
    {
     "title": "Response Delay",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 17 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(increase(grpc_client_processing_duration_seconds_sum{app=\"tls-ifacetlsoip\"}[1m])) / sum(increase(grpc_client_processing_duration_seconds_count{app=\"tls-ifacetlsoip\"}[1m]))",
       "legendFormat": "Average"
      },
      {
       "expr": "max(grpc_client_processing_duration_seconds_max{app=\"tls-ifacetlsoip\"})",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "Request Overview",
     "type": "table-old",
     "description": "The number of requests in the last hour",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 17 },
     "targets": [
      {
       "expr": "sort_desc(sum(increase(grpc_client_processing_duration_seconds_count{app=\"tls-ifacetlsoip\"}[1h])) by (service, method))"
      },
      {
       "expr": "sort_desc(sum(grpc_client_processing_duration_seconds_count{app=\"tls-ifacetlsoip\"}) by (service, method))"
      }
     ]
    },
    {
     "title": "Outgoing Requests per App",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(\n  sum(increase(grpc_client_processing_duration_seconds_count{app=\"tls-ifacetlsoip\"}[1m])) by (service)\n  * ignoring(app) group_right\n  clamp_max(count(grpc_server_processing_duration_seconds_count) by (service, app), 1)\n) by (app)",
       "legendFormat": "{{app}}"
      }
     ]
    },
    {
     "title": "Outgoing Requests per App %",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum(\n  sum(increase(grpc_client_processing_duration_seconds_count{app=\"tls-ifacetlsoip\"}[5m])) by (service)\n  * ignoring(app) group_right\n  clamp_max(count(grpc_server_processing_duration_seconds_count) by (service, app), 1)\n) by (app)",
       "legendFormat": "{{app}}"
      }
     ]
    },
    {
     "title": "Outgoing Requests per Method",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(grpc_client_processing_duration_seconds_count{app=\"tls-ifacetlsoip\"}[5m])) by (service, method) > 0",
       "legendFormat": "{{service}}/{{method}}"
      }
     ]
    },
    {
     "title": "Outgoing Requests per Method %",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(grpc_client_processing_duration_seconds_count{app=\"tls-ifacetlsoip\"}[5m])) by (service, method)",
       "legendFormat": "{{service}}/{{method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Kafka",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests / Responses",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(kafka_request_total{app=\"tls-ifacetlsoip\"}[1m])",
       "legendFormat": "Records"
      },
      {
       "expr": "-increase(kafka_response_total{app=\"tls-ifacetlsoip\"}[1m])",
       "legendFormat": "Response"
      }
     ]
    },
    {
     "title": "Kafka I/O",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "bytes", "label": "Traffic" }
     ],
     "targets": [
      {
       "expr": "increase(kafka_incoming_byte_total{app=\"tls-ifacetlsoip\"}[1m])",
       "legendFormat": "Incoming"
      },
      {
       "expr": "-increase(kafka_outgoing_byte_total{app=\"tls-ifacetlsoip\"}[1m])",
       "legendFormat": "Outgoing"
      }
     ]
    }
   ]
  },
  {
   "title": "Incoming HTTP Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Received",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(http_server_requests_seconds_count{app=\"tls-ifacetlsoip\"}[1m])) by (outcome)",
       "legendFormat": "{{outcome}}"
      }
     ]
    },
    {
     "title": "Response Delay",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 20 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(increase(http_server_requests_seconds_sum{app=\"tls-ifacetlsoip\"}[1m])) / sum(increase(http_server_requests_seconds_count{app=\"tls-ifacetlsoip\"}[1m]))",
       "legendFormat": "Average"
      },
      {
       "expr": "max(http_server_requests_seconds_max{app=\"tls-ifacetlsoip\"})",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "Request Overview",
     "type": "table-old",
     "description": "The number of requests in the last hour",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 20 },
     "targets": [
      {
       "expr": "sort_desc(sum(increase(http_server_requests_seconds_count{app=\"tls-ifacetlsoip\"}[1h])) by (method, uri)) > 0"
      },
      {
       "expr": "sort_desc(sum(http_server_requests_seconds_count{app=\"tls-ifacetlsoip\"}) by (method, uri))"
      }
     ]
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Threads used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_threads_live_threads{app=\"tls-ifacetlsoip\"})",
     "legendFormat": "JVM current threads"
    },
    {
     "expr": "sum(jvm_threads_daemon_threads{app=\"tls-ifacetlsoip\"})",
     "legendFormat": "JVM daemon threads"
    },
    {
     "expr": "sum(jvm_threads_states_threads{app=\"tls-ifacetlsoip\", state=\"blocked\"})",
     "legendFormat": "JVM deadlocked threads"
    }
   ]
  },
  {
   "title": "Log-Messages",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(log4j2_events_total{app=\"tls-ifacetlsoip\"}[5m])) by (level)",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Termination-Reasons",
   "type": "table-old",
   "description": "Reasons why this application could not start or crashed.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_last_terminated_reason{pod=~\"tls-ifacetlsoip-.*\"}) by (reason) * 0.1 > 0",
     "legendFormat": "{{reason}} (Last Reason)"
    },
    {
     "expr": "sum(kube_pod_container_status_terminated_reason{pod=~\"tls-ifacetlsoip-.*\"}) by (reason) > 0",
     "legendFormat": "{{reason}}"
    },
    {
     "expr": "sum(kube_pod_container_status_waiting_reason{pod=~\"tls-ifacetlsoip-.*\"}) by (reason) > 0",
     "legendFormat": "{{reason}}"
    }
   ]
  }
 ]
}