{
 "title": "GRPC-Services",
 "description": "GRPC-Service-Übersicht",
 "tags": [
  "spring",
  "grpc",
  "java"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Outgoing Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Sent",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(grpc_client_processing_duration_seconds_count[1m]))",
     "legendFormat": "Total Requests"
    },
    {
     "expr": "sum(increase(grpc_client_requests_sent_messages_total[1m])) / sum(increase(grpc_client_processing_duration_seconds_count[1m]))",
     "legendFormat": "Messages per Request"
    },
    {
     "expr": "sum(increase(grpc_client_responses_received_messages_total[1m])) / sum(increase(grpc_client_processing_duration_seconds_count[1m]))",
     "legendFormat": "Responses per Request"
    }
   ]
  },
  {
   "title": "Response Delay",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(increase(grpc_client_processing_duration_seconds_sum[1m])) / sum(increase(grpc_client_processing_duration_seconds_count[1m]))",
     "legendFormat": "Average"
    },
    {
     "expr": "max(grpc_client_processing_duration_seconds_max)",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Request Overview",
   "type": "table",
   "description": "The number of requests in the last hour",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "sort_desc(sum(increase(grpc_client_processing_duration_seconds_count[1h])) by (service, method))"
    },
    {
     "expr": "sort_desc(sum(grpc_client_processing_duration_seconds_count) by (service, method))"
    }
   ]
  },
  {
   "title": "Requests per App",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(grpc_client_processing_duration_seconds_count[5m])) by (app)",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Requests per App %",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(increase(grpc_client_processing_duration_seconds_count[5m])) by (app)",
     "legendFormat": "{{app}}"
    }
   ]
  },
  { "title": "Incoming Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Received",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(grpc_server_processing_duration_seconds_count[1m]))",
     "legendFormat": "Total Requests"
    },
    {
     "expr": "sum(increase(grpc_server_requests_received_messages_total[1m])) / sum(increase(grpc_server_processing_duration_seconds_count[1m]))",
     "legendFormat": "Messages per Request"
    },
    {
     "expr": "sum(increase(grpc_server_responses_sent_messages_total[1m])) / sum(increase(grpc_server_processing_duration_seconds_count[1m]))",
     "legendFormat": "Responses per Request"
    }
   ]
  },
  {
   "title": "Response Delay",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(increase(grpc_server_processing_duration_seconds_sum[1m])) / sum(increase(grpc_server_processing_duration_seconds_count[1m]))",
     "legendFormat": "Average"
    },
    {
     "expr": "max(grpc_server_processing_duration_seconds_max)",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Request Overview",
   "type": "table",
   "description": "The number of requests in the last hour",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 20 },
   "targets": [
    {
     "expr": "sort_desc(sum(increase(grpc_server_processing_duration_seconds_count[1h])) by (service, method))"
    },
    {
     "expr": "sort_desc(sum(grpc_server_processing_duration_seconds_count) by (service, method))"
    }
   ]
  },
  {
   "title": "Requests per App",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(grpc_server_processing_duration_seconds_count[5m])) by (app)",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Requests per App %",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(increase(grpc_server_processing_duration_seconds_count[5m])) by (app)",
     "legendFormat": "{{app}}"
    }
   ]
  }
 ]
}