{
 "title": "Kafka Consumer Group Overview",
 "description": "Kafka throughput grouped by consumer groups",
 "tags": [ "Kafka" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(kafka_brokers, host)"
   },
   {
    "name": "consumergroup",
    "label": "Consumer Group",
    "query": "label_values(kafka_consumergroup_lag, consumergroup)"
   }
  ]
 },
 "panels": [
  {
   "title": "Overall Produced Records Per Second",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_topic_partition_current_offset{host=\"$host\"}[1m])) by (host)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Overall Consumed Records Per Second",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_consumergroup_current_offset{host=\"$host\"}[1m])) by (host)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Consumed Records Per Second",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_consumergroup_current_offset{host=\"$host\", consumergroup=~\"$consumergroup\"}[1m])) by (consumergroup)",
     "legendFormat": "{{consumergroup}}"
    }
   ]
  },
  {
   "title": "Lag By  Consumer Group",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{host=\"$host\", consumergroup=~\"$consumergroup\"}) by (consumergroup)",
     "legendFormat": "{{consumergroup}}"
    }
   ]
  }
 ]
}